-- Launch content seed (PRD 6.1 - English at launch, Gujarati added progressively)
INSERT INTO page_text (id, page_key, block_key, content_en, content_gu) VALUES
('pt_about_title', 'about', 'title', 'About Gayatri Kamdhenu Sevatirth', NULL),
('pt_about_body', 'about', 'body', 'Gayatri Kamdhenu Sevatirth, Bhorda is affiliated with All World Gayatri Pariwar (AWGP.org), inspired by the vision of Pandit Shriram Sharma Acharya.

We welcome families, youth, and seekers to participate in seva, sadhana, yagya, education, and community upliftment at our campus in Bhorda, Gujarat.', NULL),
('pt_about_mission', 'about', 'mission', 'Our mission is to nurture seva, sadhana, and values-based living — strengthening character, compassion, and self-reliance in harmony with Gayatri Pariwar ideals.', NULL),
('pt_about_our_story_title', 'about-our-story', 'title', 'Our Story', NULL),
('pt_about_our_story_body', 'about-our-story', 'body', 'A visual journey through milestones of Gayatri Pariwar at Bhorda and beyond — from Amreshwar to the historic 108 Kundi Mahayagya.', NULL),
('pt_about_pandit_shriram_title', 'about-pandit-shriram', 'title', 'Pandit Shriram Sharma Acharya', NULL),
('pt_about_pandit_shriram_body', 'about-pandit-shriram', 'body', 'Founder of the Gayatri Pariwar movement, Pandit Shriram Sharma Acharya (1911–1990) dedicated his life to spiritual awakening, social reform, and the revival of yagya culture. His writings and guidance continue to inspire millions worldwide.', NULL),
('pt_about_mata_bhagwati_title', 'about-mata-bhagwati', 'title', 'Vandaniya Mata Bhagwati Devi Sharma', NULL),
('pt_about_mata_bhagwati_body', 'about-mata-bhagwati', 'body', 'Mata Bhagwati Devi Sharma embodied selfless seva alongside Gurudev. Her life of simplicity, courage, and devotion remains a guiding light for Gayatri Pariwar families.', NULL),
('pt_about_vedmata_gayatri_title', 'about-vedmata-gayatri', 'title', 'Vedmata Gayatri', NULL),
('pt_about_vedmata_gayatri_body', 'about-vedmata-gayatri', 'body', 'Gayatri is revered as Vedmata — the mother of the Vedas. Daily Gayatri japa and yagya sadhana form the spiritual foundation of our activities at Sevatirth Bhorda.', NULL),
('pt_about_awgp_title', 'about-awgp', 'title', 'All World Gayatri Pariwar', NULL),
('pt_about_awgp_body', 'about-awgp', 'body', 'AWGP is a global movement with millions of members, rooted in the vision of a balanced society through spirituality, education, and constructive programmes. Learn more at awgp.org.', NULL),
('pt_about_dr_chinmay_title', 'about-dr-chinmay', 'title', 'Present Mentor — Dr. Chinmay Pandya', NULL),
('pt_about_dr_chinmay_body', 'about-dr-chinmay', 'body', 'Dr. Chinmay Pandya serves as a guiding voice for Gayatri Pariwar today, carrying forward Gurudev''s mission through discourse, writing, and institutional leadership.', NULL),
('pt_about_mission_vision_title', 'about-mission-vision', 'title', 'Mission & Vision', NULL),
('pt_about_mission_vision_body', 'about-mission-vision', 'body', 'Mission: Integrate spirituality with practical living through seva, sadhana, and community programmes.

Vision: A self-reliant, values-based society where every family participates in yagya culture and constructive action.', NULL),
('pt_about_dabhoi_title', 'about-dabhoi', 'title', 'Gayatri Pariwar Dabhoi', NULL),
('pt_about_dabhoi_body', 'about-dabhoi', 'body', 'The Dabhoi centre has been a long-standing hub of Gayatri Pariwar activity in the region. Sevatirth Bhorda extends this legacy on the land generously donated for seva and sadhana.', NULL),
('pt_activity_yagya_title', 'activity-yagya', 'title', 'Yagya', NULL),
('pt_activity_yagya_body', 'activity-yagya', 'body', 'Daily and special yagyas are performed to purify the environment and consciousness. Families and volunteers are welcome to participate in havan and collective sadhana.', NULL),
('pt_activity_zhola_title', 'activity-zhola', 'title', 'Zhola Pustakalay', NULL),
('pt_activity_zhola_body', 'activity-zhola', 'body', 'A travelling library programme bringing spiritual and values-based literature to villages and schools.', NULL),
('pt_activity_trees_title', 'activity-trees', 'title', 'Tree Planting', NULL),
('pt_activity_trees_body', 'activity-trees', 'body', 'Environmental seva through tree plantation drives, organic awareness, and care for native species on campus.', NULL),
('pt_activity_sadhana_title', 'activity-sadhana', 'title', 'Sadhana', NULL),
('pt_activity_sadhana_body', 'activity-sadhana', 'body', 'Morning and evening group sadhana including Gayatri japa, meditation, and guided reflection.', NULL),
('pt_activity_daily_routine_title', 'activity-daily-routine', 'title', 'Daily Routine / Aarti', NULL),
('pt_activity_daily_routine_body', 'activity-daily-routine', 'body', 'The daily rhythm of temple aarti, meditation, and community prayer — see the schedule table below.', NULL),
('pt_activity_swadhyay_title', 'activity-swadhyay', 'title', 'Swadhyay', NULL),
('pt_activity_swadhyay_body', 'activity-swadhyay', 'body', 'Study circles on Gurudev''s literature, Vichar Kranti, and applied spirituality in daily life.', NULL),
('pt_activity_festivals_title', 'activity-festivals', 'title', 'Festival Celebrations', NULL),
('pt_activity_festivals_body', 'activity-festivals', 'body', 'Major festivals and parvas are celebrated with yagya, cultural programmes, and community meals.', NULL),
('pt_activity_farming_title', 'activity-farming', 'title', 'Organic Farming', NULL),
('pt_activity_farming_body', 'activity-farming', 'body', 'Organic cultivation on campus supports the gaushala and community kitchen with chemical-free produce.', NULL),
('pt_activity_medical_title', 'activity-medical', 'title', 'Vaccination & Medical Camps', NULL),
('pt_activity_medical_body', 'activity-medical', 'body', 'Periodic health camps and vaccination drives serve nearby villages in partnership with local volunteers.', NULL),
('pt_activity_bal_sanskar_title', 'activity-bal-sanskar', 'title', 'Bal Sanskar Shala', NULL),
('pt_activity_bal_sanskar_body', 'activity-bal-sanskar', 'body', 'Weekend values education for children through stories, games, mantra, and creative activities.', NULL),
('pt_activity_youth_title', 'activity-youth', 'title', 'Youth Cell', NULL),
('pt_activity_youth_body', 'activity-youth', 'body', 'Youth-led seva projects, leadership training, and engagement with AWGP programmes.', NULL),
('pt_activity_self_reliance_title', 'activity-self-reliance', 'title', 'Self-Reliance Training', NULL),
('pt_activity_self_reliance_body', 'activity-self-reliance', 'body', 'Skill-building workshops encouraging entrepreneurship and constructive livelihoods.', NULL),
('pt_activity_games_title', 'activity-games', 'title', 'Games / Annual Celebration', NULL),
('pt_activity_games_body', 'activity-games', 'body', 'Sports, games, and annual cultural celebrations bringing families together.', NULL),
('pt_sanskar_garbhadhan_title', 'sanskar-garbhadhan', 'title', 'Garbhadhan', NULL),
('pt_sanskar_garbhadhan_body', 'sanskar-garbhadhan', 'body', 'The Garbhadhan sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_garbhadhan_timing', 'sanskar-garbhadhan', 'timing', 'Before conception — contact for guidance', NULL),
('pt_sanskar_punsavan_title', 'sanskar-punsavan', 'title', 'Punsavan', NULL),
('pt_sanskar_punsavan_body', 'sanskar-punsavan', 'body', 'The Punsavan sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_punsavan_timing', 'sanskar-punsavan', 'timing', 'Third month of pregnancy', NULL),
('pt_sanskar_simantonayan_title', 'sanskar-simantonayan', 'title', 'Simantonayan', NULL),
('pt_sanskar_simantonayan_body', 'sanskar-simantonayan', 'body', 'The Simantonayan sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_simantonayan_timing', 'sanskar-simantonayan', 'timing', 'Seventh month of pregnancy', NULL),
('pt_sanskar_jatakarma_title', 'sanskar-jatakarma', 'title', 'Jatakarma', NULL),
('pt_sanskar_jatakarma_body', 'sanskar-jatakarma', 'body', 'The Jatakarma sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_jatakarma_timing', 'sanskar-jatakarma', 'timing', 'At birth', NULL),
('pt_sanskar_namakarana_title', 'sanskar-namakarana', 'title', 'Namakarana', NULL),
('pt_sanskar_namakarana_body', 'sanskar-namakarana', 'body', 'The Namakarana sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_namakarana_timing', 'sanskar-namakarana', 'timing', '11th day after birth', NULL),
('pt_sanskar_nishkramana_title', 'sanskar-nishkramana', 'title', 'Nishkramana', NULL),
('pt_sanskar_nishkramana_body', 'sanskar-nishkramana', 'body', 'The Nishkramana sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_nishkramana_timing', 'sanskar-nishkramana', 'timing', 'Fourth month — first outing', NULL),
('pt_sanskar_annaprashan_title', 'sanskar-annaprashan', 'title', 'Annaprashan', NULL),
('pt_sanskar_annaprashan_body', 'sanskar-annaprashan', 'body', 'The Annaprashan sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_annaprashan_timing', 'sanskar-annaprashan', 'timing', 'Sixth month — first solid food', NULL),
('pt_sanskar_chudakarana_title', 'sanskar-chudakarana', 'title', 'Chudakarana (Mundan)', NULL),
('pt_sanskar_chudakarana_body', 'sanskar-chudakarana', 'body', 'The Chudakarana (Mundan) sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_chudakarana_timing', 'sanskar-chudakarana', 'timing', 'First year or third year — mundan', NULL),
('pt_sanskar_karnavedha_title', 'sanskar-karnavedha', 'title', 'Karnavedha', NULL),
('pt_sanskar_karnavedha_body', 'sanskar-karnavedha', 'body', 'The Karnavedha sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_karnavedha_timing', 'sanskar-karnavedha', 'timing', 'Third or fifth year', NULL),
('pt_sanskar_vidyarambha_title', 'sanskar-vidyarambha', 'title', 'Vidyarambha', NULL),
('pt_sanskar_vidyarambha_body', 'sanskar-vidyarambha', 'body', 'The Vidyarambha sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_vidyarambha_timing', 'sanskar-vidyarambha', 'timing', 'Age 3–5 — beginning of learning', NULL),
('pt_sanskar_upanayana_title', 'sanskar-upanayana', 'title', 'Upanayana', NULL),
('pt_sanskar_upanayana_body', 'sanskar-upanayana', 'body', 'The Upanayana sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_upanayana_timing', 'sanskar-upanayana', 'timing', 'Age 8–12 — sacred thread', NULL),
('pt_sanskar_vedarambha_title', 'sanskar-vedarambha', 'title', 'Vedarambha', NULL),
('pt_sanskar_vedarambha_body', 'sanskar-vedarambha', 'body', 'The Vedarambha sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_vedarambha_timing', 'sanskar-vedarambha', 'timing', 'After Upanayana — study of Vedas', NULL),
('pt_sanskar_samavartana_title', 'sanskar-samavartana', 'title', 'Samavartana', NULL),
('pt_sanskar_samavartana_body', 'sanskar-samavartana', 'body', 'The Samavartana sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_samavartana_timing', 'sanskar-samavartana', 'timing', 'Completion of formal study', NULL),
('pt_sanskar_vivaha_title', 'sanskar-vivaha', 'title', 'Vivaha', NULL),
('pt_sanskar_vivaha_body', 'sanskar-vivaha', 'body', 'The Vivaha sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_vivaha_timing', 'sanskar-vivaha', 'timing', 'Marriage — by appointment', NULL),
('pt_sanskar_vanaprastha_title', 'sanskar-vanaprastha', 'title', 'Vanaprastha', NULL),
('pt_sanskar_vanaprastha_body', 'sanskar-vanaprastha', 'body', 'The Vanaprastha sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_vanaprastha_timing', 'sanskar-vanaprastha', 'timing', 'Transition to spiritual retirement', NULL),
('pt_sanskar_antyesti_title', 'sanskar-antyesti', 'title', 'Antyesti', NULL),
('pt_sanskar_antyesti_body', 'sanskar-antyesti', 'body', 'The Antyesti sanskar is performed according to Vedic tradition at Sevatirth Bhorda. Our priests and volunteers guide families through preparation, mantras, and the ceremony itself.', NULL),
('pt_sanskar_antyesti_timing', 'sanskar-antyesti', 'timing', 'Final rites — contact for support', NULL),
('pt_gaushala_title', 'gaushala', 'title', 'Gaushala', NULL),
('pt_gaushala_body', 'gaushala', 'body', 'Cow seva is central to our campus life. The gaushala provides care, fodder, and medical attention for cows while promoting organic farming and Gau Seva opportunities for devotees.', NULL),
('pt_gurukul_title', 'gurukul', 'title', 'Gurukul', NULL),
('pt_gurukul_body', 'gurukul', 'body', 'Values-based education for children and youth — combining academic support, sanskar, sports, and daily sadhana in a Gurukul atmosphere.', NULL),
('pt_home_hero_title', 'home', 'hero_title', 'Welcome to Gayatri Kamdhenu Sevatirth', NULL),
('pt_home_hero_lead', 'home', 'hero_lead', 'A living centre of seva, sadhana, and Gayatri Pariwar values in Bhorda — welcoming families, seekers, and volunteers.', NULL),
('pt_home_highlight_gaushala', 'home', 'highlight_gaushala', 'Cow seva, organic care, and Gau Seva opportunities for the community.', NULL),
('pt_home_highlight_gurukul', 'home', 'highlight_gurukul', 'Values-based learning for children and youth rooted in Indian culture.', NULL),
('pt_home_highlight_mavtardham', 'home', 'highlight_mavtardham', 'A sacred space for remembrance, prayer, and quiet reflection.', NULL),
('pt_home_updates_teaser', 'home', 'updates_teaser', 'Explore spotlight events, the weekly schedule, and gallery highlights from campus life.', NULL),
('pt_home_connect_cta', 'home', 'connect_cta', 'Share your interest in seva, visits, donations, or volunteering — our team will respond personally.', NULL)
ON CONFLICT(page_key, block_key) DO UPDATE SET
  content_en = excluded.content_en,
  content_gu = COALESCE(excluded.content_gu, page_text.content_gu);

-- Spotlight events
INSERT INTO spotlight_events (id, type, title_en, title_gu, desc_en, desc_gu, date_start, date_end, location, photo_url, status) VALUES
('se_mahayagya_2023', 'Festival', '108 Kundi Mahayagya', NULL,
 'The historic 108 Kundi Mahayagya at Bhorda brought together thousands of participants for collective havan and spiritual renewal.',
 NULL, '2023-11-01', '2023-11-09', 'Sevatirth Bhorda campus', NULL, 'past'),
('se_weekly_yagya', 'Event', 'Weekly Community Yagya', NULL,
 'Open community yagya every Sunday morning. Families welcome — please arrive 15 minutes early for seating.',
 NULL, '2026-08-24', NULL, 'Main yagya shala', NULL, 'published'),
('se_gurukul_open', 'Shibir', 'Gurukul Open Day', NULL,
 'Visit classrooms, meet teachers, and learn about values-based programmes for children and youth.',
 NULL, '2026-09-14', NULL, 'Gurukul building', NULL, 'published')
ON CONFLICT(id) DO UPDATE SET
  title_en = excluded.title_en,
  desc_en = excluded.desc_en,
  date_start = excluded.date_start,
  status = excluded.status;

-- Video gallery (YouTube links — PRD §6.4)
INSERT INTO gallery_video (id, youtube_url, thumbnail_url, title_en, title_gu, desc_en, desc_gu, event_id, day_number) VALUES
('gv_awgp_intro', 'https://www.youtube.com/watch?v=lw2l0aLBMRA', NULL,
 'Gayatri Pariwar — message of Gurudev', NULL,
 'Inspirational message from the Gayatri Pariwar tradition. Replace with your preferred AWGP video via admin.', NULL, NULL, NULL),
('gv_mahayagya_day1', 'https://www.youtube.com/watch?v=lw2l0aLBMRA', NULL,
 '108 Kundi Mahayagya — Day 1', NULL,
 'Highlights from the first day of the Mahayagya at Bhorda.', NULL, 'se_mahayagya_2023', 1)
ON CONFLICT(id) DO UPDATE SET
  youtube_url = excluded.youtube_url,
  title_en = excluded.title_en,
  desc_en = excluded.desc_en;
